name: Release aTox

on:
  push:
    tags:
      - 'v*'

jobs:
  draft_release:
    name: Draft release
    runs-on: ubuntu-18.04
    outputs:
      upload_url: ${{ steps.create_release_draft.outputs.upload_url }}
    steps:
      - name: Create release draft
        id: create_release_draft
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true

  # TODO This is copied from "bazel" in ci.yaml.
  build_and_upload_release:
    name: Build and upload release artifacts
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    # Failed to create a Robolectric sandbox: Android SDK 29 requires Java 9
    - uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Set up Android
      run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;$NDK_VERSION" | grep -v = || true
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/$NDK_VERSION" >> $GITHUB_ENV
      env:
        NDK_VERSION: 21.3.6528147
    - name: Install
      run: wget https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64 --output-document=bazelisk
    - name: Build
      run: bazelisk build //...

    - name: Upload APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.draft_release.upload_url }}
        asset_path: path/to/atox.apk # :(
        asset_name: atox.apk
        asset_content_type: application/zip
